/* Generated By:JavaCC: Do not edit this line. EG2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 4;
  /** RegularExpression Id. */
  int CONDITION = 5;
  /** RegularExpression Id. */
  int STATUS = 6;
  /** RegularExpression Id. */
  int VERB = 7;
  /** RegularExpression Id. */
  int OpMode = 8;
  /** RegularExpression Id. */
  int AGENT = 9;
  /** RegularExpression Id. */
  int STAKEHOLDERS = 10;
  /** RegularExpression Id. */
  int OPERATION = 11;
  /** RegularExpression Id. */
  int OBJECT = 12;
  /** RegularExpression Id. */
  int Parameter = 13;
  /** RegularExpression Id. */
  int Conj = 14;
  /** RegularExpression Id. */
  int EFFECT = 15;
  /** RegularExpression Id. */
  int VALUE = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int users = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<ID>",
    "<CONDITION>",
    "<STATUS>",
    "<VERB>",
    "<OpMode>",
    "<AGENT>",
    "<STAKEHOLDERS>",
    "<OPERATION>",
    "<OBJECT>",
    "<Parameter>",
    "<Conj>",
    "<EFFECT>",
    "<VALUE>",
    "<STRING>",
    "<DIGIT>",
    "<LETTER>",
    "<users>",
    "\":\"",
    "\" \"",
    "\".\"",
    "\"a \"",
    "\"an \"",
    "\"the \"",
    "\"The \"",
    "\"be \"",
    "\" to\"",
    "\"for \"",
    "\"in \"",
    "\"the\"",
    "\"about \"",
    "\"through \"",
    "\"The\"",
    "\"there are \"",
    "\"is \"",
  };

}
